# Generated by Django 3.2.16 on 2022-12-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=200, unique=True, verbose_name='name')),
                ('color', models.CharField(help_text='Цвет в HEX', max_length=7, unique=True, verbose_name='color')),
                ('slug', models.CharField(help_text='Уникальный слаг', max_length=200, unique=True, verbose_name='slug')),
            ],
        ),
    ]
