# Generated by Django 3.2.16 on 2022-12-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Тег  в рецепте', 'verbose_name_plural': 'Теги в рецептах'},
        ),
        migrations.AddConstraint(
            model_name='tagrecipe',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='tag_and_recipe_unit_have_unique_relationships'),
        ),
    ]
