# Generated by Django 3.2.16 on 2022-12-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20221227_0910'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='name_and_measurement_unit_have_unique_relationships',
        ),
    ]
