# Generated by Django 3.2.16 on 2022-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_ingredient_name_and_measurement_unit_have_unique_relationships'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='name_and_measurement_unit_have_unique_relationships'),
        ),
    ]
